config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'
  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [ :new, :create, :destroy ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, :through => :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :ingredient_id, :scope => [:cocktail_id]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @dose = Dose.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render "doses/new"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(params[:cocktail_id])
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Here is the list of all the cocktails</h1>
      <ul>
        <% @cocktails.each do |cocktail| %>
          <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
        <% end %>
      </ul>

      <%= link_to "Add a cocktail", new_cocktail_path %>
    </div>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Add a new cocktail</h1>

      <%= simple_form_for @cocktail do |f| %>
      <%= f.input :name %>
      <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <%= link_to "Go back", cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Here is the detail of the <%= @cocktail.name %></h1>
      <% @cocktail.doses.each do |dose| %>
        <p>👉  <%= dose.description %>  <%= dose.ingredient.name %>
        <%= link_to "🗑",
                  cocktail_dose_path(@cocktail, dose),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></p>
      <% end %>

      <div><%= link_to "Go back", cocktails_path %></div>
      <%= link_to "Add a dose", new_cocktail_dose_path(@cocktail) %>
   </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Add a new Dose</h1>
      <% @cocktail.ingredients.each do |ingredient| %>
        <p><%= ingredient.name %></p>
      <% end %>

      <%= simple_form_for([@cocktail, @dose], url: cocktail_doses_path(@cocktail)) do |f| %>
        <%= f.input :description %>
        <%= f.association :ingredient %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
      <%= link_to "Go back", cocktail_path(@cocktail) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>